baseURL = 'https://podcasts.groong.org/'
languageCode = 'en-us'
title = 'Groong Podcast'
theme = "castanet-1.19.0" 
googleAnalytics = 'G-JNZ5XF71ZR'
paginate = "9"
buildFuture = true
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"
	blog = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "01about"
    url = "/about"

[[Menu.Main]]
    name = "Blog"
    identifier = "02blog"
    url = "/blog"

[[Menu.Main]]
    name = "Bios"
    identifier = "03bios"
    url = "/bios"

[[Menu.Main]]
    name = "Hosts"
    identifier = "04hosts"
    parent = "03bios"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "05guests"
    parent = "03bios"
    url = "/guest"

[[Menu.Main]]
    name = "Content"
    identifier = "06content"
    url = "/content"

[[Menu.Main]]
    name = "Categories"
    identifier = "07categories"
    parent = "06content"
    url = "/categories"

[[Menu.Main]]
    name = "Series"
    identifier = "08series"
    parent = "06content"
    url = "/series"

[[Menu.Main]]
    name = "Tags"
    identifier = "09tags"
    parent = "06content"
    url = "/tags"

[[Menu.Main]]
    name = "Upcoming"
    identifier = "10upcoming"
    url = "/upcoming"

[[Menu.Main]]
    name = "Donate ❤️"
    identifier = "11donate"
    url = "/donate"

[params]
mainSections = ["episode"]
episode_number_style  = "brackets"
episode_number_prefix = "EP"
site_theme = "blue"
# site_layout = "grid"
site_layout = "row"
show_next_upcoming = "true"
enable_jumbo = "true"
# enable_jumbo = "false"
disable_title_caps = "true"
# truncate = "100"
about_logo = "/img/groong.jpg"
copyright_notice = "Copyright 2025 [Armenian News Network - Groong](https://groong.org)"
youtube_subscribe = "https://www.youtube.com/c/groong?sub_confirmation=1"
itunes_subscribe = "https://podcasts.apple.com/us/podcast/armenian-news-network-groong-week-in-review-podcast/id1524235399?ign-mpt=uo%3D4&mt=2"
# android_subscribe = "https://www.subscribeonandroid.com/feeds.buzzsprout.com/1215113.rss"
spotify_subscribe = "https://open.spotify.com/show/53y8G068hkWOvE6W0LUjDK?si=75f22dec938947a1&nd=1"
rss_subscribe = "https://feeds.buzzsprout.com/1215113.rss"
description = "Armenian News Network/Groong, an Armenian podcast providing objective coverage on Armenia, Artsakh (Nagorno Karabakh) and the Armenian diaspora. Find us and follow us everywhere on social media. Here are our links: [linktr.ee/groong](https://linktr.ee/groong)."

media_prefix = "https://www.buzzsprout.com/1215113/"
disqusShortname = "groong-podcast"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

  # Social links can be given in full URL form or short form
  # In the short form the theme will generate a relevant URL
  [params.social]
    facebook = "groong.org"
    facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "groong"
    twitter_domain = "groong.org" # This domain shows in twitter cards as "View on `twitter_domain`"
    instagram = "anngroong"
    youtube = "groong"
    telegram = "anngroong"

  [params.authors]

    [params.authors.Asbed]
      name = "Asbed Bedrossian"
      thumbnail = "img/host/asbed_sm.webp"
      Pronouns = ""
      bio = "Asbed is founder of Groong and co-founder of the ANN/Groong podcast."
      [params.authors.Asbed.social]
        facebook = "qubriq"
        twitter = "qubriq"
        github = ""
        linkedin = ""
        homepage = ""
        pinterest = ""
        instagram = ""
        youtube = ""
        twitch = ""

    [params.authors.Hovik]
      name = "Hovik Manucharyan"
      thumbnail = "img/host/hovik_sm.webp"
      Pronouns = ""
      bio = "Hovik Manucharyan is co-founder of the ANN/Groong podcast and a contributor to Groong news since the late 1990s."
      [params.authors.Hovik.social]
        facebook = "HovikYerevan"
        twitter = "HovikYerevan"
        github = ""
        linkedin = ""
        homepage = ""
        pinterest = ""
        instagram = ""
        youtube = "HovikYerevan"
        twitch = ""

    [params.links]
      [params.links.ado]
        name = "Armenian News Network/Groong"
        url = "https://www.groong.org"
